### ISSUE TITLE
Cannot output to file in 2.93.1

### ISSUE THREAD

**Issue by c3f59** [atticus-lv/RenderStackNode#16]
- Whenever rendering I get an error message: `Render error (Permission denied) cannot save: '.png'`.
- The path is on a Network Drive in a writable folder. The file name is `$label\$blend_$camera_$res_$T{%m-%d}CF$T{%H-%M}BLR`
- Does the same with other file formats.

![image](https://user-images.githubusercontent.com/45612174/127353185-1b99aca7-19dd-429b-bf7d-e3d90c25c0a8.png)

**Comment by atticus-lv** [comment]
Can you try to replace '\\' with '/'? I think this may cause the problem?
And I think you are using the develop version.Since I have make some changes to the update system, you are recommded to use the new nodes(which have the input sockets) instead of the old node. In this case, you may need to use a scene file path node to overwrite the path

**Comment by c3f59** [comment]
Thanks for your input.
I have rebuilt the tree as per your instructions.
![image](https://user-images.githubusercontent.com/45612174/127474989-290d45a1-b991-4aba-bf57-d511d4b0f1aa.png)

- Works: File Output now works as expected. The base path can be specified as Windows does with `\` backslash.
- Works: create subfolder with a `/` slash in Path Exp
- Does not work: Path Exp `$label/$blend_$camera_$res_$T{%m-%d}CF$T{%H-%M}BLR` creates the `$label` folder, but then also creates a folder `$blend`, while omitting `$blend` from the file name.
See Issue #17
